# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboardPyranha.ui'
#
# Created: Fri May 16 10:24:02 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

from QCharButton import QCharButton
from QFunctionButton import QFunctionButton

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(860, 280)
        Form.setStyleSheet(_fromUtf8("color:#3ea700"))
        self.charButton_1_1 = QCharButton(Form)
        self.charButton_1_1.setGeometry(QtCore.QRect(0, 145, 40, 40))
        self.charButton_1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_1.setFont(font)
        self.charButton_1_1.setObjectName(_fromUtf8("charButton_1_1"))
        self.charButton_1_2 = QCharButton(Form)
        self.charButton_1_2.setGeometry(QtCore.QRect(45, 145, 40, 40))
        self.charButton_1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_2.setFont(font)
        self.charButton_1_2.setObjectName(_fromUtf8("charButton_1_2"))
        self.charButton_1_3 = QCharButton(Form)
        self.charButton_1_3.setGeometry(QtCore.QRect(90, 145, 40, 40))
        self.charButton_1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_3.setFont(font)
        self.charButton_1_3.setObjectName(_fromUtf8("charButton_1_3"))
        self.charButton_1_4 = QCharButton(Form)
        self.charButton_1_4.setGeometry(QtCore.QRect(135, 145, 40, 40))
        self.charButton_1_4.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_4.setFont(font)
        self.charButton_1_4.setObjectName(_fromUtf8("charButton_1_4"))
        self.charButton_1_5 = QCharButton(Form)
        self.charButton_1_5.setGeometry(QtCore.QRect(180, 145, 40, 40))
        self.charButton_1_5.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_5.setFont(font)
        self.charButton_1_5.setObjectName(_fromUtf8("charButton_1_5"))
        self.charButton_1_7 = QCharButton(Form)
        self.charButton_1_7.setGeometry(QtCore.QRect(270, 145, 40, 40))
        self.charButton_1_7.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_7.setFont(font)
        self.charButton_1_7.setObjectName(_fromUtf8("charButton_1_7"))
        self.charButton_1_6 = QCharButton(Form)
        self.charButton_1_6.setGeometry(QtCore.QRect(225, 145, 40, 40))
        self.charButton_1_6.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_6.setFont(font)
        self.charButton_1_6.setObjectName(_fromUtf8("charButton_1_6"))
        self.charButton_1_8 = QCharButton(Form)
        self.charButton_1_8.setGeometry(QtCore.QRect(315, 145, 40, 40))
        self.charButton_1_8.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_8.setFont(font)
        self.charButton_1_8.setObjectName(_fromUtf8("charButton_1_8"))
        self.charButton_1_9 = QCharButton(Form)
        self.charButton_1_9.setGeometry(QtCore.QRect(360, 145, 40, 40))
        self.charButton_1_9.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_1_9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_9.setFont(font)
        self.charButton_1_9.setObjectName(_fromUtf8("charButton_1_9"))
        self.charButton_3_8 = QCharButton(Form)
        self.charButton_3_8.setGeometry(QtCore.QRect(315, 235, 40, 40))
        self.charButton_3_8.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_8.setFont(font)
        self.charButton_3_8.setObjectName(_fromUtf8("charButton_3_8"))
        self.charButton_2_1 = QCharButton(Form)
        self.charButton_2_1.setGeometry(QtCore.QRect(0, 190, 40, 40))
        self.charButton_2_1.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_1.setFont(font)
        self.charButton_2_1.setObjectName(_fromUtf8("charButton_2_1"))
        self.charButton_2_2 = QCharButton(Form)
        self.charButton_2_2.setGeometry(QtCore.QRect(45, 190, 40, 40))
        self.charButton_2_2.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_2.setFont(font)
        self.charButton_2_2.setObjectName(_fromUtf8("charButton_2_2"))
        self.charButton_2_3 = QCharButton(Form)
        self.charButton_2_3.setGeometry(QtCore.QRect(90, 190, 40, 40))
        self.charButton_2_3.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_3.setFont(font)
        self.charButton_2_3.setObjectName(_fromUtf8("charButton_2_3"))
        self.charButton_2_4 = QCharButton(Form)
        self.charButton_2_4.setGeometry(QtCore.QRect(135, 190, 40, 40))
        self.charButton_2_4.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_4.setFont(font)
        self.charButton_2_4.setObjectName(_fromUtf8("charButton_2_4"))
        self.charButton_2_5 = QCharButton(Form)
        self.charButton_2_5.setGeometry(QtCore.QRect(180, 190, 40, 40))
        self.charButton_2_5.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_5.setFont(font)
        self.charButton_2_5.setObjectName(_fromUtf8("charButton_2_5"))
        self.charButton_2_6 = QCharButton(Form)
        self.charButton_2_6.setGeometry(QtCore.QRect(225, 190, 40, 40))
        self.charButton_2_6.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_6.setFont(font)
        self.charButton_2_6.setObjectName(_fromUtf8("charButton_2_6"))
        self.charButton_2_7 = QCharButton(Form)
        self.charButton_2_7.setGeometry(QtCore.QRect(270, 190, 40, 40))
        self.charButton_2_7.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_7.setFont(font)
        self.charButton_2_7.setObjectName(_fromUtf8("charButton_2_7"))
        self.charButton_2_8 = QCharButton(Form)
        self.charButton_2_8.setGeometry(QtCore.QRect(315, 190, 40, 40))
        self.charButton_2_8.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_8.setFont(font)
        self.charButton_2_8.setObjectName(_fromUtf8("charButton_2_8"))
        self.charButton_2_9 = QCharButton(Form)
        self.charButton_2_9.setGeometry(QtCore.QRect(360, 190, 40, 40))
        self.charButton_2_9.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_2_9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_9.setFont(font)
        self.charButton_2_9.setObjectName(_fromUtf8("charButton_2_9"))
        self.charButton_3_9 = QCharButton(Form)
        self.charButton_3_9.setGeometry(QtCore.QRect(360, 235, 40, 40))
        self.charButton_3_9.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_9.setFont(font)
        self.charButton_3_9.setObjectName(_fromUtf8("charButton_3_9"))
        self.charButton_3_5 = QCharButton(Form)
        self.charButton_3_5.setGeometry(QtCore.QRect(180, 235, 40, 40))
        self.charButton_3_5.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_5.setFont(font)
        self.charButton_3_5.setObjectName(_fromUtf8("charButton_3_5"))
        self.charButton_3_4 = QCharButton(Form)
        self.charButton_3_4.setGeometry(QtCore.QRect(135, 235, 40, 40))
        self.charButton_3_4.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_4.setFont(font)
        self.charButton_3_4.setObjectName(_fromUtf8("charButton_3_4"))
        self.charButton_3_1 = QCharButton(Form)
        self.charButton_3_1.setGeometry(QtCore.QRect(0, 235, 40, 40))
        self.charButton_3_1.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_1.setFont(font)
        self.charButton_3_1.setObjectName(_fromUtf8("charButton_3_1"))
        self.charButton_3_6 = QCharButton(Form)
        self.charButton_3_6.setGeometry(QtCore.QRect(225, 235, 40, 40))
        self.charButton_3_6.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_6.setFont(font)
        self.charButton_3_6.setObjectName(_fromUtf8("charButton_3_6"))
        self.charButton_3_7 = QCharButton(Form)
        self.charButton_3_7.setGeometry(QtCore.QRect(270, 235, 40, 40))
        self.charButton_3_7.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_7.setFont(font)
        self.charButton_3_7.setObjectName(_fromUtf8("charButton_3_7"))
        self.charButton_3_3 = QCharButton(Form)
        self.charButton_3_3.setGeometry(QtCore.QRect(90, 235, 40, 40))
        self.charButton_3_3.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_3.setFont(font)
        self.charButton_3_3.setObjectName(_fromUtf8("charButton_3_3"))
        self.charButton_3_2 = QCharButton(Form)
        self.charButton_3_2.setGeometry(QtCore.QRect(45, 235, 40, 40))
        self.charButton_3_2.setMinimumSize(QtCore.QSize(40, 40))
        self.charButton_3_2.setMaximumSize(QtCore.QSize(40, 40))
        self.charButton_3_2.setFont(font)
        self.charButton_3_2.setObjectName(_fromUtf8("charButton_3_2"))
        
        
        
        self.modeButtonNum = QCharButton(Form)
        self.modeButtonNum.setGeometry(QtCore.QRect(180, 55, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonNum.setFont(font)
        self.modeButtonNum.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonNum.setObjectName(_fromUtf8("modeButtonNum"))
        self.modeButtonSym = QCharButton(Form)
        self.modeButtonSym.setGeometry(QtCore.QRect(0, 55, 85, 40))
        self.modeButtonSym.setFont(font)
        self.modeButtonSym.setObjectName(_fromUtf8("modeButtonSym"))
        self.modeButtonMedia = QCharButton(Form)
        self.modeButtonMedia.setGeometry(QtCore.QRect(270, 55, 85, 40))
        self.modeButtonMedia.setFont(font)
        self.modeButtonMedia.setStyleSheet(_fromUtf8("color:#fd750f"))
        self.modeButtonMedia.setObjectName(_fromUtf8("modeButtonMedia"))
        self.modeButtonF = QCharButton(Form)
        self.modeButtonF.setGeometry(QtCore.QRect(360, 55, 40, 40))
        self.modeButtonF.setMinimumSize(QtCore.QSize(40, 40))
        self.modeButtonF.setMaximumSize(QtCore.QSize(40, 40))
        self.modeButtonF.setFont(font)
        self.modeButtonF.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonF.setObjectName(_fromUtf8("modeButtonF"))
        self.modeButtonWeb = QCharButton(Form)
        self.modeButtonWeb.setGeometry(QtCore.QRect(90, 55, 85, 40))
        self.modeButtonWeb.setFont(font)
        self.modeButtonWeb.setAutoFillBackground(False)
        self.modeButtonWeb.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.modeButtonWeb.setObjectName(_fromUtf8("modeButtonWeb"))
        self.funButton_1_1 = QFunctionButton(Form)
        self.funButton_1_1.setGeometry(QtCore.QRect(0, 100, 40, 40))
        self.funButton_1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_1.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_1.setObjectName(_fromUtf8("funButton_1_1"))
        self.funButton_1_2 = QFunctionButton(Form)
        self.funButton_1_2.setGeometry(QtCore.QRect(45, 100, 40, 40))
        self.funButton_1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_2.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_2.setObjectName(_fromUtf8("funButton_1_2"))
        self.funButton_1_3 = QFunctionButton(Form)
        self.funButton_1_3.setGeometry(QtCore.QRect(90, 100, 40, 40))
        self.funButton_1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_3.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_3.setObjectName(_fromUtf8("funButton_1_3"))
        self.funButton_1_6 = QFunctionButton(Form)
        self.funButton_1_6.setGeometry(QtCore.QRect(225, 100, 40, 40))
        self.funButton_1_6.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_6.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_6.setObjectName(_fromUtf8("funButton_1_6"))
        self.funButton_1_7 = QFunctionButton(Form)
        self.funButton_1_7.setGeometry(QtCore.QRect(270, 100, 40, 40))
        self.funButton_1_7.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_7.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_7.setObjectName(_fromUtf8("funButton_1_7"))
        self.funButton_1_8 = QFunctionButton(Form)
        self.funButton_1_8.setGeometry(QtCore.QRect(315, 100, 40, 40))
        self.funButton_1_8.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_8.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_8.setObjectName(_fromUtf8("funButton_1_8"))
        self.funButton_1_9 = QFunctionButton(Form)
        self.funButton_1_9.setGeometry(QtCore.QRect(360, 100, 40, 40))
        self.funButton_1_9.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_9.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_9.setObjectName(_fromUtf8("funButton_1_9"))
        self.funButton_1_5 = QFunctionButton(Form)
        self.funButton_1_5.setGeometry(QtCore.QRect(180, 100, 40, 40))
        self.funButton_1_5.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_5.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_5.setObjectName(_fromUtf8("funButton_1_5"))
        self.funButton_1_4 = QFunctionButton(Form)
        self.funButton_1_4.setGeometry(QtCore.QRect(135, 100, 40, 40))
        self.funButton_1_4.setMinimumSize(QtCore.QSize(40, 40))
        self.funButton_1_4.setMaximumSize(QtCore.QSize(40, 40))
        self.funButton_1_4.setObjectName(_fromUtf8("funButton_1_4"))
        self.predectiveLineEdit_1 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_1.setGeometry(QtCore.QRect(0, 10, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predectiveLineEdit_1.setFont(font)
        self.predectiveLineEdit_1.setObjectName(_fromUtf8("predectiveLineEdit_1"))
        self.predectiveLineEdit_2 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_2.setGeometry(QtCore.QRect(135, 10, 130, 40))
        self.predectiveLineEdit_2.setFont(font)
        self.predectiveLineEdit_2.setObjectName(_fromUtf8("predectiveLineEdit_2"))
        self.predectiveLineEdit_3 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_3.setGeometry(QtCore.QRect(270, 10, 130, 40))
        self.predectiveLineEdit_3.setFont(font)
        self.predectiveLineEdit_3.setObjectName(_fromUtf8("predectiveLineEdit_3"))
        self.webButton_2_4 = QCharButton(Form)
        self.webButton_2_4.setGeometry(QtCore.QRect(545, 55, 40, 40))
        self.webButton_2_4.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_2_4.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_2_4.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_4.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_4.setIcon(icon)
        self.webButton_2_4.setObjectName(_fromUtf8("webButton_2_4"))
        self.webButton_1_3 = QCharButton(Form)
        self.webButton_1_3.setGeometry(QtCore.QRect(500, 10, 40, 40))
        self.webButton_1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_1_3.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_1_3.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_3.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_new_tab.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_3.setIcon(icon1)
        self.webButton_1_3.setObjectName(_fromUtf8("webButton_1_3"))
        self.webButton_1_1 = QCharButton(Form)
        self.webButton_1_1.setGeometry(QtCore.QRect(410, 10, 40, 40))
        self.webButton_1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_1_1.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_1_1.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_1.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_1.setIcon(icon2)
        self.webButton_1_1.setObjectName(_fromUtf8("webButton_1_1"))
        self.webButton_4_3 = QCharButton(Form)
        self.webButton_4_3.setGeometry(QtCore.QRect(500, 145, 41, 40))
        self.webButton_4_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_3.setObjectName(_fromUtf8("webButton_4_3"))
        self.webButton_1_2 = QCharButton(Form)
        self.webButton_1_2.setGeometry(QtCore.QRect(455, 10, 40, 40))
        self.webButton_1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_1_2.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_1_2.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_2.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_2.setIcon(icon3)
        self.webButton_1_2.setObjectName(_fromUtf8("webButton_1_2"))
        self.webButton_3_2 = QCharButton(Form)
        self.webButton_3_2.setGeometry(QtCore.QRect(455, 100, 40, 40))
        self.webButton_3_2.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_3_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_2.setFont(font)
        self.webButton_3_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_2.setObjectName(_fromUtf8("webButton_3_2"))
        self.webButton_2_3 = QCharButton(Form)
        self.webButton_2_3.setGeometry(QtCore.QRect(500, 55, 40, 40))
        self.webButton_2_3.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_2_3.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_2_3.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_3.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_zoom_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_3.setIcon(icon4)
        self.webButton_2_3.setObjectName(_fromUtf8("webButton_2_3"))
        self.webButton_4_4 = QCharButton(Form)
        self.webButton_4_4.setGeometry(QtCore.QRect(545, 145, 41, 40))
        self.webButton_4_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_4.setObjectName(_fromUtf8("webButton_4_4"))
        self.webButton_3_3 = QCharButton(Form)
        self.webButton_3_3.setGeometry(QtCore.QRect(500, 100, 40, 40))
        self.webButton_3_3.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_3_3.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_3_3.setFont(font)
        self.webButton_3_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_3.setObjectName(_fromUtf8("webButton_3_3"))
        self.webButton_1_5 = QCharButton(Form)
        self.webButton_1_5.setGeometry(QtCore.QRect(590, 10, 40, 40))
        self.webButton_1_5.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_1_5.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_1_5.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_5.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_5.setIcon(icon5)
        self.webButton_1_5.setObjectName(_fromUtf8("webButton_1_5"))
        self.webButton_3_5 = QCharButton(Form)
        self.webButton_3_5.setGeometry(QtCore.QRect(590, 100, 40, 40))
        self.webButton_3_5.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_3_5.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_3_5.setFont(font)
        self.webButton_3_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_5.setObjectName(_fromUtf8("webButton_3_5"))
        self.webButton_5_1 = QCharButton(Form)
        self.webButton_5_1.setGeometry(QtCore.QRect(410, 190, 40, 40))
        self.webButton_5_1.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_5_1.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_5_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_5_1.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_go_urlbar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_5_1.setIcon(icon6)
        self.webButton_5_1.setObjectName(_fromUtf8("webButton_5_1"))
        self.webButton_4_1 = QCharButton(Form)
        self.webButton_4_1.setGeometry(QtCore.QRect(410, 145, 41, 40))
        self.webButton_4_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_1.setObjectName(_fromUtf8("webButton_4_1"))
        self.webButton_3_1 = QCharButton(Form)
        self.webButton_3_1.setGeometry(QtCore.QRect(410, 100, 40, 40))
        self.webButton_3_1.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_3_1.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_3_1.setFont(font)
        self.webButton_3_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_1.setObjectName(_fromUtf8("webButton_3_1"))
        self.webButton_5_5 = QCharButton(Form)
        self.webButton_5_5.setGeometry(QtCore.QRect(590, 190, 40, 40))
        self.webButton_5_5.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_5_5.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_5_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_5_5.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_5_5.setIcon(icon7)
        self.webButton_5_5.setObjectName(_fromUtf8("webButton_5_5"))
        self.webButton_2_2 = QCharButton(Form)
        self.webButton_2_2.setGeometry(QtCore.QRect(455, 55, 40, 40))
        self.webButton_2_2.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_2_2.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_2_2.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_2.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_2.setIcon(icon8)
        self.webButton_2_2.setObjectName(_fromUtf8("webButton_2_2"))
        self.webButton_2_5 = QCharButton(Form)
        self.webButton_2_5.setGeometry(QtCore.QRect(590, 55, 40, 40))
        self.webButton_2_5.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_2_5.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_2_5.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_5.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_5.setIcon(icon9)
        self.webButton_2_5.setObjectName(_fromUtf8("webButton_2_5"))
        self.webButton_5_2 = QCharButton(Form)
        self.webButton_5_2.setGeometry(QtCore.QRect(455, 190, 40, 40))
        self.webButton_5_2.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_5_2.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_5_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_5_2.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_5_2.setIcon(icon10)
        self.webButton_5_2.setObjectName(_fromUtf8("webButton_5_2"))
        self.webButton_4_2 = QCharButton(Form)
        self.webButton_4_2.setGeometry(QtCore.QRect(455, 145, 41, 40))
        self.webButton_4_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_2.setObjectName(_fromUtf8("webButton_4_2"))
        self.webButton_2_1 = QCharButton(Form)
        self.webButton_2_1.setGeometry(QtCore.QRect(410, 55, 40, 40))
        self.webButton_2_1.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_2_1.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_2_1.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_1.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_1.setIcon(icon11)
        self.webButton_2_1.setObjectName(_fromUtf8("webButton_2_1"))
        self.webButton_1_4 = QCharButton(Form)
        self.webButton_1_4.setGeometry(QtCore.QRect(545, 10, 40, 40))
        self.webButton_1_4.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_1_4.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_1_4.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_4.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_4.setIcon(icon12)
        self.webButton_1_4.setObjectName(_fromUtf8("webButton_1_4"))
        self.webButton_5_3 = QCharButton(Form)
        self.webButton_5_3.setGeometry(QtCore.QRect(500, 190, 40, 40))
        self.webButton_5_3.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_5_3.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_5_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_5_3.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_tab_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_5_3.setIcon(icon13)
        self.webButton_5_3.setObjectName(_fromUtf8("webButton_5_3"))
        self.webButton_3_4 = QCharButton(Form)
        self.webButton_3_4.setGeometry(QtCore.QRect(545, 100, 40, 40))
        self.webButton_3_4.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_3_4.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_3_4.setFont(font)
        self.webButton_3_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_4.setObjectName(_fromUtf8("webButton_3_4"))
        self.webButton_5_4 = QCharButton(Form)
        self.webButton_5_4.setGeometry(QtCore.QRect(545, 190, 40, 40))
        self.webButton_5_4.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_5_4.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_5_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_5_4.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_tab_rigth.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_5_4.setIcon(icon14)
        self.webButton_5_4.setObjectName(_fromUtf8("webButton_5_4"))
        self.webButton_4_5 = QCharButton(Form)
        self.webButton_4_5.setGeometry(QtCore.QRect(590, 145, 41, 40))
        self.webButton_4_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_5.setObjectName(_fromUtf8("webButton_4_5"))
        
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_go_text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        #Media Buttons
        #Play
        self.mediaButton_1_1 = QCharButton(Form)
        self.mediaButton_1_1.setGeometry(QtCore.QRect(640, 55, 40, 40))
        self.mediaButton_1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_1.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_1.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_1_1.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_1_1.setIcon(icon20)
        self.mediaButton_1_1.setObjectName(_fromUtf8("mediaButton_1_1"))
        #Stop
        self.mediaButton_1_2 = QCharButton(Form)
        self.mediaButton_1_2.setGeometry(QtCore.QRect(685, 55, 40, 40))
        self.mediaButton_1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_2.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_2.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_1_2.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_1_2.setIcon(icon18)
        self.mediaButton_1_2.setObjectName(_fromUtf8("mediaButton_1_2"))
        #Pause
        self.mediaButton_1_3 = QCharButton(Form)
        self.mediaButton_1_3.setGeometry(QtCore.QRect(730, 55, 40, 40))
        self.mediaButton_1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_3.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_3.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_1_3.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_1_3.setIcon(icon16)
        self.mediaButton_1_3.setObjectName(_fromUtf8("mediaButton_1_3"))
        #rewind
        self.mediaButton_1_4 = QCharButton(Form)
        self.mediaButton_1_4.setGeometry(QtCore.QRect(775, 55, 40, 40))
        self.mediaButton_1_4.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_4.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_4.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_1_4.setText(_fromUtf8(""))
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_rwd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_1_4.setIcon(icon28)
        self.mediaButton_1_4.setObjectName(_fromUtf8("mediaButton_1_4"))
        #foward
        self.mediaButton_1_5 = QCharButton(Form)
        self.mediaButton_1_5.setGeometry(QtCore.QRect(820, 55, 40, 40))
        self.mediaButton_1_5.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_5.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_1_5.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_1_5.setText(_fromUtf8(""))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_fast_fwd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_1_5.setIcon(icon27)
        self.mediaButton_1_5.setObjectName(_fromUtf8("mediaButton_1_5"))
        #previous
        self.mediaButton_2_1 = QCharButton(Form)
        self.mediaButton_2_1.setGeometry(QtCore.QRect(640, 100, 40, 40))
        self.mediaButton_2_1.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_1.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_1.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_2_1.setText(_fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_2_1.setIcon(icon21)
        self.mediaButton_2_1.setObjectName(_fromUtf8("mediaButton_2_1"))
        #Mute
        self.mediaButton_2_2 = QCharButton(Form)
        self.mediaButton_2_2.setGeometry(QtCore.QRect(685, 100, 40, 40))
        self.mediaButton_2_2.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_2.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_2.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_2_2.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_mute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_2_2.setIcon(icon15)
        self.mediaButton_2_2.setObjectName(_fromUtf8("mediaButton_2_2"))
        #Volume Down
        self.mediaButton_2_3 = QCharButton(Form)
        self.mediaButton_2_3.setGeometry(QtCore.QRect(730, 100, 40, 40))
        self.mediaButton_2_3.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_3.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_3.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_2_3.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_volume_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_2_3.setIcon(icon19)
        self.mediaButton_2_3.setObjectName(_fromUtf8("mediaButton_2_3"))
        #Volume Up
        self.mediaButton_2_4 = QCharButton(Form)
        self.mediaButton_2_4.setGeometry(QtCore.QRect(775, 100, 40, 40))
        self.mediaButton_2_4.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_4.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_4.setStyleSheet(_fromUtf8("color:blue"))
        self.mediaButton_2_4.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("img/media_volume_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaButton_2_4.setIcon(icon17)
        self.mediaButton_2_4.setObjectName(_fromUtf8("mediaButton_2_4"))
        #Go Text
        self.mediaButton_2_5 = QCharButton(Form)
        self.mediaButton_2_5.setGeometry(QtCore.QRect(820, 100, 40, 40))
        self.mediaButton_2_5.setMinimumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_5.setMaximumSize(QtCore.QSize(40, 40))
        self.mediaButton_2_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.mediaButton_2_5.setText(_fromUtf8(""))
        self.mediaButton_2_5.setIcon(icon25)
        self.mediaButton_2_5.setObjectName(_fromUtf8("mediaButton_2_5"))
        
        
        
        
        self.webButton_6_4 = QCharButton(Form)
        self.webButton_6_4.setGeometry(QtCore.QRect(545, 235, 40, 40))
        self.webButton_6_4.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_6_4.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_6_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_6_4.setText(_fromUtf8(""))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_6_4.setIcon(icon22)
        self.webButton_6_4.setObjectName(_fromUtf8("webButton_6_4"))
        self.webButton_6_2 = QCharButton(Form)
        self.webButton_6_2.setGeometry(QtCore.QRect(455, 235, 40, 40))
        self.webButton_6_2.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_6_2.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_6_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_6_2.setText(_fromUtf8(""))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_hostory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_6_2.setIcon(icon23)
        self.webButton_6_2.setObjectName(_fromUtf8("webButton_6_2"))
        self.webButton_6_1 = QCharButton(Form)
        self.webButton_6_1.setGeometry(QtCore.QRect(410, 235, 40, 40))
        self.webButton_6_1.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_6_1.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_6_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_6_1.setText(_fromUtf8(""))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_favorites.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_6_1.setIcon(icon24)
        self.webButton_6_1.setObjectName(_fromUtf8("webButton_6_1"))
        self.webButton_6_5 = QCharButton(Form)
        self.webButton_6_5.setGeometry(QtCore.QRect(590, 235, 40, 40))
        self.webButton_6_5.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_6_5.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_6_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_6_5.setText(_fromUtf8(""))
        self.webButton_6_5.setIcon(icon25)
        self.webButton_6_5.setObjectName(_fromUtf8("webButton_6_5"))
        self.webButton_6_3 = QCharButton(Form)
        self.webButton_6_3.setGeometry(QtCore.QRect(500, 235, 40, 40))
        self.webButton_6_3.setMinimumSize(QtCore.QSize(40, 40))
        self.webButton_6_3.setMaximumSize(QtCore.QSize(40, 40))
        self.webButton_6_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_6_3.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_6_3.setIcon(icon26)
        self.webButton_6_3.setObjectName(_fromUtf8("webButton_6_3"))
        
        self.numButton_2_4 = QCharButton(Form)
        self.numButton_2_4.setGeometry(QtCore.QRect(775, 190, 40, 40))
        self.numButton_2_4.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_2_4.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_2_4.setFont(font)
        self.numButton_2_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_4.setObjectName(_fromUtf8("numButton_2_4"))
        self.numButton_1_3 = QCharButton(Form)
        self.numButton_1_3.setGeometry(QtCore.QRect(730, 145, 40, 40))
        self.numButton_1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_1_3.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_1_3.setFont(font)
        self.numButton_1_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_3.setObjectName(_fromUtf8("numButton_1_3"))
        self.numButton_2_1 = QCharButton(Form)
        self.numButton_2_1.setGeometry(QtCore.QRect(640, 190, 40, 40))
        self.numButton_2_1.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_2_1.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_2_1.setFont(font)
        self.numButton_2_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_1.setObjectName(_fromUtf8("numButton_2_1"))
        self.numButton_2_2 = QCharButton(Form)
        self.numButton_2_2.setGeometry(QtCore.QRect(685, 190, 40, 40))
        self.numButton_2_2.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_2_2.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_2_2.setFont(font)
        self.numButton_2_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_2.setObjectName(_fromUtf8("numButton_2_2"))
        self.numButton_1_4 = QCharButton(Form)
        self.numButton_1_4.setGeometry(QtCore.QRect(775, 145, 40, 40))
        self.numButton_1_4.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_1_4.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_1_4.setFont(font)
        self.numButton_1_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_4.setObjectName(_fromUtf8("numButton_1_4"))
        self.numButton_2_5 = QCharButton(Form)
        self.numButton_2_5.setGeometry(QtCore.QRect(820, 190, 40, 40))
        self.numButton_2_5.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_2_5.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_2_5.setFont(font)
        self.numButton_2_5.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_5.setObjectName(_fromUtf8("numButton_2_5"))
        self.numButton_2_3 = QCharButton(Form)
        self.numButton_2_3.setGeometry(QtCore.QRect(730, 190, 40, 40))
        self.numButton_2_3.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_2_3.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_2_3.setFont(font)
        self.numButton_2_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_3.setObjectName(_fromUtf8("numButton_2_3"))
        self.numButton_1_5 = QCharButton(Form)
        self.numButton_1_5.setGeometry(QtCore.QRect(820, 145, 40, 40))
        self.numButton_1_5.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_1_5.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_1_5.setFont(font)
        self.numButton_1_5.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_5.setObjectName(_fromUtf8("numButton_1_5"))
        self.numButton_1_1 = QCharButton(Form)
        self.numButton_1_1.setGeometry(QtCore.QRect(640, 145, 40, 40))
        self.numButton_1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_1_1.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_1_1.setFont(font)
        self.numButton_1_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_1.setObjectName(_fromUtf8("numButton_1_1"))
        self.numButton_1_2 = QCharButton(Form)
        self.numButton_1_2.setGeometry(QtCore.QRect(685, 145, 40, 40))
        self.numButton_1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_1_2.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_1_2.setFont(font)
        self.numButton_1_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_2.setObjectName(_fromUtf8("numButton_1_2"))
        self.numButton_3_4 = QCharButton(Form)
        self.numButton_3_4.setGeometry(QtCore.QRect(775, 235, 40, 40))
        self.numButton_3_4.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_3_4.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_3_4.setFont(font)
        self.numButton_3_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_4.setObjectName(_fromUtf8("numButton_3_4"))
        self.numButton_3_2 = QCharButton(Form)
        self.numButton_3_2.setGeometry(QtCore.QRect(685, 235, 40, 40))
        self.numButton_3_2.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_3_2.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_3_2.setFont(font)
        self.numButton_3_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_2.setObjectName(_fromUtf8("numButton_3_2"))
        self.numButton_3_3 = QCharButton(Form)
        self.numButton_3_3.setGeometry(QtCore.QRect(730, 235, 40, 40))
        self.numButton_3_3.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_3_3.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_3_3.setFont(font)
        self.numButton_3_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_3.setObjectName(_fromUtf8("numButton_3_3"))
        self.numButton_3_1 = QCharButton(Form)
        self.numButton_3_1.setGeometry(QtCore.QRect(640, 235, 40, 40))
        self.numButton_3_1.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_3_1.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_3_1.setFont(font)
        self.numButton_3_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_1.setObjectName(_fromUtf8("numButton_3_1"))
        self.numButton_3_5 = QCharButton(Form)
        self.numButton_3_5.setGeometry(QtCore.QRect(820, 235, 40, 40))
        self.numButton_3_5.setMinimumSize(QtCore.QSize(40, 40))
        self.numButton_3_5.setMaximumSize(QtCore.QSize(40, 40))
        self.numButton_3_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.numButton_3_5.setText(_fromUtf8(""))
        self.numButton_3_5.setIcon(icon25)
        self.numButton_3_5.setObjectName(_fromUtf8("numButton_3_5"))
        self.TitleLineEdit = QtGui.QLineEdit(Form)
        self.TitleLineEdit.setGeometry(QtCore.QRect(640, 10, 220, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Purisa"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.TitleLineEdit.setFont(font)
        self.TitleLineEdit.setStyleSheet(_fromUtf8("border:0px; background:transparent"))
        self.TitleLineEdit.setObjectName(_fromUtf8("TitleLineEdit"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.charButton_1_1.setText(_translate("Form", "q", None))
        self.charButton_1_2.setText(_translate("Form", "w", None))
        self.charButton_1_3.setText(_translate("Form", "e", None))
        self.charButton_1_4.setText(_translate("Form", "r", None))
        self.charButton_1_5.setText(_translate("Form", "t", None))
        self.charButton_1_7.setText(_translate("Form", "u", None))
        self.charButton_1_6.setText(_translate("Form", "y", None))
        self.charButton_1_8.setText(_translate("Form", "i", None))
        self.charButton_1_9.setText(_translate("Form", "o", None))
        self.charButton_3_8.setText(_translate("Form", "p", None))
        self.charButton_2_1.setText(_translate("Form", "a", None))
        self.charButton_2_2.setText(_translate("Form", "s", None))
        self.charButton_2_3.setText(_translate("Form", "d", None))
        self.charButton_2_4.setText(_translate("Form", "f", None))
        self.charButton_2_5.setText(_translate("Form", "g", None))
        self.charButton_2_6.setText(_translate("Form", "h", None))
        self.charButton_2_7.setText(_translate("Form", "j", None))
        self.charButton_2_8.setText(_translate("Form", "k", None))
        self.charButton_2_9.setText(_translate("Form", "l", None))
        self.charButton_3_9.setText(_translate("Form", "ñ", None))
        self.charButton_3_5.setText(_translate("Form", "b", None))
        self.charButton_3_4.setText(_translate("Form", "v", None))
        self.charButton_3_1.setText(_translate("Form", "z", None))
        self.charButton_3_6.setText(_translate("Form", "n", None))
        self.charButton_3_7.setText(_translate("Form", "m", None))
        self.charButton_3_3.setText(_translate("Form", "c", None))
        self.charButton_3_2.setText(_translate("Form", "x", None))
        self.funButton_1_2.setText(_translate("Form", "Ent", None))
        self.funButton_1_3.setText(_translate("Form", "Sup", None))
        self.modeButtonNum.setText(_translate("Form", "Num", None))
        self.modeButtonSym.setText(_translate("Form", "Sym", None))
        self.modeButtonMedia.setText(_translate("Form", "Media", None))
        self.modeButtonF.setText(_translate("Form", "F?", None))
        self.modeButtonWeb.setText(_translate("Form", "Web", None))
        self.funButton_1_6.setText(_translate("Form", "Esc", None))
        self.funButton_1_7.setText(_translate("Form", "Ins", None))
        self.funButton_1_8.setText(_translate("Form", "Ctl", None))
        self.funButton_1_9.setText(_translate("Form", "Alt", None))
        self.funButton_1_1.setText(_translate("Form", "May", None))
        self.funButton_1_5.setText(_translate("Form", "Tab", None))
        self.funButton_1_4.setText(_translate("Form", "Bsp", None))
        self.predectiveLineEdit_1.setText(_translate("Form", "Palabra 1", None))
        self.predectiveLineEdit_2.setText(_translate("Form", "Palabra 2", None))
        self.predectiveLineEdit_3.setText(_translate("Form", "Palabra 3", None))
        self.webButton_4_3.setText(_translate("Form", ".net", None))
        self.webButton_3_2.setText(_translate("Form", "/", None))
        self.webButton_4_4.setText(_translate("Form", ".org", None))
        self.webButton_3_3.setText(_translate("Form", ".", None))
        self.webButton_3_5.setText(_translate("Form", "_", None))
        self.webButton_4_1.setText(_translate("Form", "www", None))
        self.webButton_3_1.setText(_translate("Form", "@", None))
        self.webButton_4_2.setText(_translate("Form", ".com", None))
        self.webButton_3_4.setText(_translate("Form", "-", None))
        self.webButton_4_5.setText(_translate("Form", "http", None))
        self.numButton_2_4.setText(_translate("Form", "8", None))
        self.numButton_1_3.setText(_translate("Form", "2", None))
        self.numButton_2_1.setText(_translate("Form", "5", None))
        self.numButton_2_2.setText(_translate("Form", "6", None))
        self.numButton_1_4.setText(_translate("Form", "3", None))
        self.numButton_2_5.setText(_translate("Form", "9", None))
        self.numButton_2_3.setText(_translate("Form", "7", None))
        self.numButton_1_5.setText(_translate("Form", "4", None))
        self.numButton_1_1.setText(_translate("Form", "0", None))
        self.numButton_1_2.setText(_translate("Form", "1", None))
        self.numButton_3_4.setText(_translate("Form", "/", None))
        self.numButton_3_2.setText(_translate("Form", "-", None))
        self.numButton_3_3.setText(_translate("Form", "*", None))
        self.numButton_3_1.setText(_translate("Form", "+", None))
        self.TitleLineEdit.setText(_translate("Form", "Pyranha Keyboard", None))

