# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/silvio/Datos/Dropbox/Tesina/Pyranha/Workspace/Pyranha/keyboardMousePyranha.ui'
#
# Created: Tue Jun 17 21:23:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from QModeButton import QModeButton
from QMouseButton import QMouseButton
from QBackButton import QBackButton

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(775, 255)
        Form.setStyleSheet(_fromUtf8("color:#3ea700"))
        self.charButton_1_1 = QtGui.QPushButton(Form)
        self.charButton_1_1.setGeometry(QtCore.QRect(0, 130, 35, 35))
        self.charButton_1_1.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_1.setFont(font)
        self.charButton_1_1.setObjectName(_fromUtf8("charButton_1_1"))
        self.charButton_1_2 = QtGui.QPushButton(Form)
        self.charButton_1_2.setGeometry(QtCore.QRect(40, 130, 35, 35))
        self.charButton_1_2.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_2.setFont(font)
        self.charButton_1_2.setObjectName(_fromUtf8("charButton_1_2"))
        self.charButton_1_3 = QtGui.QPushButton(Form)
        self.charButton_1_3.setGeometry(QtCore.QRect(80, 130, 35, 35))
        self.charButton_1_3.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_3.setFont(font)
        self.charButton_1_3.setObjectName(_fromUtf8("charButton_1_3"))
        self.charButton_1_4 = QtGui.QPushButton(Form)
        self.charButton_1_4.setGeometry(QtCore.QRect(120, 130, 35, 35))
        self.charButton_1_4.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_4.setFont(font)
        self.charButton_1_4.setObjectName(_fromUtf8("charButton_1_4"))
        self.charButton_1_5 = QtGui.QPushButton(Form)
        self.charButton_1_5.setGeometry(QtCore.QRect(160, 130, 35, 35))
        self.charButton_1_5.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_5.setFont(font)
        self.charButton_1_5.setObjectName(_fromUtf8("charButton_1_5"))
        self.charButton_1_7 = QtGui.QPushButton(Form)
        self.charButton_1_7.setGeometry(QtCore.QRect(240, 130, 35, 35))
        self.charButton_1_7.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_7.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_7.setFont(font)
        self.charButton_1_7.setObjectName(_fromUtf8("charButton_1_7"))
        self.charButton_1_6 = QtGui.QPushButton(Form)
        self.charButton_1_6.setGeometry(QtCore.QRect(200, 130, 35, 35))
        self.charButton_1_6.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_6.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_6.setFont(font)
        self.charButton_1_6.setObjectName(_fromUtf8("charButton_1_6"))
        self.charButton_1_8 = QtGui.QPushButton(Form)
        self.charButton_1_8.setGeometry(QtCore.QRect(280, 130, 35, 35))
        self.charButton_1_8.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_8.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_8.setFont(font)
        self.charButton_1_8.setObjectName(_fromUtf8("charButton_1_8"))
        self.charButton_1_9 = QtGui.QPushButton(Form)
        self.charButton_1_9.setGeometry(QtCore.QRect(320, 130, 35, 35))
        self.charButton_1_9.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_1_9.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_1_9.setFont(font)
        self.charButton_1_9.setObjectName(_fromUtf8("charButton_1_9"))
        self.charButton_3_8 = QtGui.QPushButton(Form)
        self.charButton_3_8.setGeometry(QtCore.QRect(280, 210, 35, 35))
        self.charButton_3_8.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_8.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_8.setFont(font)
        self.charButton_3_8.setObjectName(_fromUtf8("charButton_3_8"))
        self.charButton_2_1 = QtGui.QPushButton(Form)
        self.charButton_2_1.setGeometry(QtCore.QRect(0, 170, 35, 35))
        self.charButton_2_1.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_1.setFont(font)
        self.charButton_2_1.setObjectName(_fromUtf8("charButton_2_1"))
        self.charButton_2_2 = QtGui.QPushButton(Form)
        self.charButton_2_2.setGeometry(QtCore.QRect(40, 170, 35, 35))
        self.charButton_2_2.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_2.setFont(font)
        self.charButton_2_2.setObjectName(_fromUtf8("charButton_2_2"))
        self.charButton_2_3 = QtGui.QPushButton(Form)
        self.charButton_2_3.setGeometry(QtCore.QRect(80, 170, 35, 35))
        self.charButton_2_3.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_3.setFont(font)
        self.charButton_2_3.setObjectName(_fromUtf8("charButton_2_3"))
        self.charButton_2_4 = QtGui.QPushButton(Form)
        self.charButton_2_4.setGeometry(QtCore.QRect(120, 170, 35, 35))
        self.charButton_2_4.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_4.setFont(font)
        self.charButton_2_4.setObjectName(_fromUtf8("charButton_2_4"))
        self.charButton_2_5 = QtGui.QPushButton(Form)
        self.charButton_2_5.setGeometry(QtCore.QRect(160, 170, 35, 35))
        self.charButton_2_5.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_5.setFont(font)
        self.charButton_2_5.setObjectName(_fromUtf8("charButton_2_5"))
        self.charButton_2_6 = QtGui.QPushButton(Form)
        self.charButton_2_6.setGeometry(QtCore.QRect(200, 170, 35, 35))
        self.charButton_2_6.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_6.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_6.setFont(font)
        self.charButton_2_6.setObjectName(_fromUtf8("charButton_2_6"))
        self.charButton_2_7 = QtGui.QPushButton(Form)
        self.charButton_2_7.setGeometry(QtCore.QRect(240, 170, 35, 35))
        self.charButton_2_7.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_7.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_7.setFont(font)
        self.charButton_2_7.setObjectName(_fromUtf8("charButton_2_7"))
        self.charButton_2_8 = QtGui.QPushButton(Form)
        self.charButton_2_8.setGeometry(QtCore.QRect(280, 170, 35, 35))
        self.charButton_2_8.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_8.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_8.setFont(font)
        self.charButton_2_8.setObjectName(_fromUtf8("charButton_2_8"))
        self.charButton_2_9 = QtGui.QPushButton(Form)
        self.charButton_2_9.setGeometry(QtCore.QRect(320, 170, 35, 35))
        self.charButton_2_9.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_2_9.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_2_9.setFont(font)
        self.charButton_2_9.setObjectName(_fromUtf8("charButton_2_9"))
        self.charButton_3_9 = QtGui.QPushButton(Form)
        self.charButton_3_9.setGeometry(QtCore.QRect(320, 210, 35, 35))
        self.charButton_3_9.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_9.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_9.setFont(font)
        self.charButton_3_9.setObjectName(_fromUtf8("charButton_3_9"))
        self.charButton_3_5 = QtGui.QPushButton(Form)
        self.charButton_3_5.setGeometry(QtCore.QRect(160, 210, 35, 35))
        self.charButton_3_5.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_5.setFont(font)
        self.charButton_3_5.setObjectName(_fromUtf8("charButton_3_5"))
        self.charButton_3_4 = QtGui.QPushButton(Form)
        self.charButton_3_4.setGeometry(QtCore.QRect(120, 210, 35, 35))
        self.charButton_3_4.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_4.setFont(font)
        self.charButton_3_4.setObjectName(_fromUtf8("charButton_3_4"))
        self.charButton_3_1 = QtGui.QPushButton(Form)
        self.charButton_3_1.setGeometry(QtCore.QRect(0, 210, 35, 35))
        self.charButton_3_1.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_1.setFont(font)
        self.charButton_3_1.setObjectName(_fromUtf8("charButton_3_1"))
        self.charButton_3_6 = QtGui.QPushButton(Form)
        self.charButton_3_6.setGeometry(QtCore.QRect(200, 210, 35, 35))
        self.charButton_3_6.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_6.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_6.setFont(font)
        self.charButton_3_6.setObjectName(_fromUtf8("charButton_3_6"))
        self.charButton_3_7 = QtGui.QPushButton(Form)
        self.charButton_3_7.setGeometry(QtCore.QRect(240, 210, 35, 35))
        self.charButton_3_7.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_7.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_7.setFont(font)
        self.charButton_3_7.setObjectName(_fromUtf8("charButton_3_7"))
        self.charButton_3_3 = QtGui.QPushButton(Form)
        self.charButton_3_3.setGeometry(QtCore.QRect(80, 210, 35, 35))
        self.charButton_3_3.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_3.setFont(font)
        self.charButton_3_3.setObjectName(_fromUtf8("charButton_3_3"))
        self.charButton_3_2 = QtGui.QPushButton(Form)
        self.charButton_3_2.setGeometry(QtCore.QRect(40, 210, 35, 35))
        self.charButton_3_2.setMinimumSize(QtCore.QSize(35, 35))
        self.charButton_3_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charButton_3_2.setFont(font)
        self.charButton_3_2.setObjectName(_fromUtf8("charButton_3_2"))
        self.funButton_1_2 = QtGui.QPushButton(Form)
        self.funButton_1_2.setGeometry(QtCore.QRect(40, 90, 35, 35))
        self.funButton_1_2.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_2.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_2.setObjectName(_fromUtf8("funButton_1_2"))
        self.funButton_1_3 = QtGui.QPushButton(Form)
        self.funButton_1_3.setGeometry(QtCore.QRect(80, 90, 35, 35))
        self.funButton_1_3.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_3.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_3.setObjectName(_fromUtf8("funButton_1_3"))
        
        
        
        self.funButton_1_6 = QtGui.QPushButton(Form)
        self.funButton_1_6.setGeometry(QtCore.QRect(200, 90, 35, 35))
        self.funButton_1_6.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_6.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_6.setObjectName(_fromUtf8("funButton_1_6"))
        self.funButton_1_7 = QtGui.QPushButton(Form)
        self.funButton_1_7.setGeometry(QtCore.QRect(240, 90, 35, 35))
        self.funButton_1_7.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_7.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_7.setObjectName(_fromUtf8("funButton_1_7"))
        self.funButton_1_8 = QtGui.QPushButton(Form)
        self.funButton_1_8.setGeometry(QtCore.QRect(280, 90, 35, 35))
        self.funButton_1_8.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_8.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_8.setObjectName(_fromUtf8("funButton_1_8"))
        self.funButton_1_9 = QtGui.QPushButton(Form)
        self.funButton_1_9.setGeometry(QtCore.QRect(320, 90, 35, 35))
        self.funButton_1_9.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_9.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_9.setObjectName(_fromUtf8("funButton_1_9"))
        self.funButton_1_1 = QtGui.QPushButton(Form)
        self.funButton_1_1.setGeometry(QtCore.QRect(0, 90, 35, 35))
        self.funButton_1_1.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_1.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_1.setObjectName(_fromUtf8("funButton_1_1"))
        self.funButton_1_5 = QtGui.QPushButton(Form)
        self.funButton_1_5.setGeometry(QtCore.QRect(160, 90, 35, 35))
        self.funButton_1_5.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_5.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_5.setObjectName(_fromUtf8("funButton_1_5"))
        self.funButton_1_4 = QtGui.QPushButton(Form)
        self.funButton_1_4.setGeometry(QtCore.QRect(120, 90, 35, 35))
        self.funButton_1_4.setMinimumSize(QtCore.QSize(35, 35))
        self.funButton_1_4.setMaximumSize(QtCore.QSize(35, 35))
        self.funButton_1_4.setObjectName(_fromUtf8("funButton_1_4"))
        self.predectiveLineEdit_1 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_1.setGeometry(QtCore.QRect(0, 10, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predectiveLineEdit_1.setFont(font)
        self.predectiveLineEdit_1.setObjectName(_fromUtf8("predectiveLineEdit_1"))
        self.predectiveLineEdit_2 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_2.setGeometry(QtCore.QRect(120, 10, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predectiveLineEdit_2.setFont(font)
        self.predectiveLineEdit_2.setObjectName(_fromUtf8("predectiveLineEdit_2"))
        self.predectiveLineEdit_3 = QtGui.QLineEdit(Form)
        self.predectiveLineEdit_3.setGeometry(QtCore.QRect(240, 10, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predectiveLineEdit_3.setFont(font)
        self.predectiveLineEdit_3.setObjectName(_fromUtf8("predectiveLineEdit_3"))
        self.webButton_2_4 = QtGui.QPushButton(Form)
        self.webButton_2_4.setGeometry(QtCore.QRect(490, 130, 35, 35))
        self.webButton_2_4.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_2_4.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_2_4.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_4.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_4.setIcon(icon4)
        self.webButton_2_4.setObjectName(_fromUtf8("webButton_2_4"))
        self.webButton_1_3 = QtGui.QPushButton(Form)
        self.webButton_1_3.setGeometry(QtCore.QRect(450, 90, 35, 35))
        self.webButton_1_3.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_1_3.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_1_3.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_3.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_new_tab.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_3.setIcon(icon5)
        self.webButton_1_3.setObjectName(_fromUtf8("webButton_1_3"))
        self.webButton_1_1 = QtGui.QPushButton(Form)
        self.webButton_1_1.setGeometry(QtCore.QRect(370, 90, 35, 35))
        self.webButton_1_1.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_1_1.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_1_1.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_1.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_1.setIcon(icon6)
        self.webButton_1_1.setObjectName(_fromUtf8("webButton_1_1"))
        self.webButton_4_3 = QtGui.QPushButton(Form)
        self.webButton_4_3.setGeometry(QtCore.QRect(450, 210, 35, 35))
        self.webButton_4_3.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_4_3.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_4_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_3.setObjectName(_fromUtf8("webButton_4_3"))
        self.webButton_1_2 = QtGui.QPushButton(Form)
        self.webButton_1_2.setGeometry(QtCore.QRect(410, 90, 35, 35))
        self.webButton_1_2.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_1_2.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_1_2.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_2.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_2.setIcon(icon7)
        self.webButton_1_2.setObjectName(_fromUtf8("webButton_1_2"))
        self.webButton_3_2 = QtGui.QPushButton(Form)
        self.webButton_3_2.setGeometry(QtCore.QRect(410, 170, 35, 35))
        self.webButton_3_2.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_3_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_2.setFont(font)
        self.webButton_3_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_2.setObjectName(_fromUtf8("webButton_3_2"))
        self.webButton_2_3 = QtGui.QPushButton(Form)
        self.webButton_2_3.setGeometry(QtCore.QRect(450, 130, 35, 35))
        self.webButton_2_3.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_2_3.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_2_3.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_3.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_zoom_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_3.setIcon(icon8)
        self.webButton_2_3.setObjectName(_fromUtf8("webButton_2_3"))
        self.webButton_4_4 = QtGui.QPushButton(Form)
        self.webButton_4_4.setGeometry(QtCore.QRect(490, 210, 35, 35))
        self.webButton_4_4.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_4_4.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_4_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_4.setObjectName(_fromUtf8("webButton_4_4"))
        self.webButton_3_3 = QtGui.QPushButton(Form)
        self.webButton_3_3.setGeometry(QtCore.QRect(450, 170, 35, 35))
        self.webButton_3_3.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_3_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_3.setFont(font)
        self.webButton_3_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_3.setObjectName(_fromUtf8("webButton_3_3"))
        self.webButton_1_5 = QtGui.QPushButton(Form)
        self.webButton_1_5.setGeometry(QtCore.QRect(530, 90, 35, 35))
        self.webButton_1_5.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_1_5.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_1_5.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_5.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_5.setIcon(icon9)
        self.webButton_1_5.setObjectName(_fromUtf8("webButton_1_5"))
        self.webButton_3_5 = QtGui.QPushButton(Form)
        self.webButton_3_5.setGeometry(QtCore.QRect(530, 170, 35, 35))
        self.webButton_3_5.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_3_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_5.setFont(font)
        self.webButton_3_5.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_5.setObjectName(_fromUtf8("webButton_3_5"))
        self.webButton_4_1 = QtGui.QPushButton(Form)
        self.webButton_4_1.setGeometry(QtCore.QRect(370, 210, 35, 35))
        self.webButton_4_1.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_4_1.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_4_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_1.setObjectName(_fromUtf8("webButton_4_1"))
        self.webButton_3_1 = QtGui.QPushButton(Form)
        self.webButton_3_1.setGeometry(QtCore.QRect(370, 170, 35, 35))
        self.webButton_3_1.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_3_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_1.setFont(font)
        self.webButton_3_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_1.setObjectName(_fromUtf8("webButton_3_1"))
        self.webButton_2_2 = QtGui.QPushButton(Form)
        self.webButton_2_2.setGeometry(QtCore.QRect(410, 130, 35, 35))
        self.webButton_2_2.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_2_2.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_2_2.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_2.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_2.setIcon(icon10)
        self.webButton_2_2.setObjectName(_fromUtf8("webButton_2_2"))
        self.webButton_2_5 = QtGui.QPushButton(Form)
        self.webButton_2_5.setGeometry(QtCore.QRect(530, 130, 35, 35))
        self.webButton_2_5.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_2_5.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_2_5.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_5.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_5.setIcon(icon11)
        self.webButton_2_5.setObjectName(_fromUtf8("webButton_2_5"))
        self.webButton_4_2 = QtGui.QPushButton(Form)
        self.webButton_4_2.setGeometry(QtCore.QRect(410, 210, 35, 35))
        self.webButton_4_2.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_4_2.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_4_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_4_2.setObjectName(_fromUtf8("webButton_4_2"))
        self.webButton_2_1 = QtGui.QPushButton(Form)
        self.webButton_2_1.setGeometry(QtCore.QRect(370, 130, 35, 35))
        self.webButton_2_1.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_2_1.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_2_1.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_2_1.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2_1.setIcon(icon12)
        self.webButton_2_1.setObjectName(_fromUtf8("webButton_2_1"))
        self.webButton_1_4 = QtGui.QPushButton(Form)
        self.webButton_1_4.setGeometry(QtCore.QRect(490, 90, 35, 35))
        self.webButton_1_4.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_1_4.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_1_4.setStyleSheet(_fromUtf8("color:blue"))
        self.webButton_1_4.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_1_4.setIcon(icon13)
        self.webButton_1_4.setObjectName(_fromUtf8("webButton_1_4"))
        self.webButton_3_4 = QtGui.QPushButton(Form)
        self.webButton_3_4.setGeometry(QtCore.QRect(490, 170, 35, 35))
        self.webButton_3_4.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_3_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webButton_3_4.setFont(font)
        self.webButton_3_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_3_4.setObjectName(_fromUtf8("webButton_3_4"))
        
        ####################################################################################################
        self.mouseButton_l_d = QMouseButton(Form)
        self.mouseButton_l_d.action = "ld"
        self.mouseButton_l_d.setGeometry(QtCore.QRect(600, 90, 35, 35))
        self.mouseButton_l_d.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_l_d.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_l_d.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_l_d.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_l_d.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_l_d.setIcon(icon14)
        self.mouseButton_l_d.setObjectName(_fromUtf8("mouseButton_l_d"))
        
        self.mouseButton_r_u = QMouseButton(Form)
        self.mouseButton_r_u.action = "ru"
        self.mouseButton_r_u.setGeometry(QtCore.QRect(680, 10, 35, 35))
        self.mouseButton_r_u.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_r_u.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_r_u.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_r_u.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_r_u.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_r_u.setIcon(icon15)
        self.mouseButton_r_u.setObjectName(_fromUtf8("mouseButton_r_u"))
        
        self.mouseButton_r_d = QMouseButton(Form)
        self.mouseButton_r_d.action = "rd"
        self.mouseButton_r_d.setGeometry(QtCore.QRect(680, 90, 35, 35))
        self.mouseButton_r_d.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_r_d.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_r_d.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_r_d.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_r_d.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_r_d.setIcon(icon16)
        self.mouseButton_r_d.setObjectName(_fromUtf8("mouseButton_r_d"))
        
        self.mouseButton_u = QMouseButton(Form)
        self.mouseButton_u.action = "u"
        self.mouseButton_u.setGeometry(QtCore.QRect(640, 10, 35, 35))
        self.mouseButton_u.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_u.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_u.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_u.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_u.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_u.setIcon(icon17)
        self.mouseButton_u.setObjectName(_fromUtf8("mouseButton_u"))
        
        self.mouseButton_d = QMouseButton(Form)
        self.mouseButton_d.action = "d"
        self.mouseButton_d.setGeometry(QtCore.QRect(640, 90, 35, 35))
        self.mouseButton_d.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_d.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_d.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_d.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_d.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_d.setIcon(icon18)
        self.mouseButton_d.setObjectName(_fromUtf8("mouseButton_d"))
        
        self.mouseButton_l_u = QMouseButton(Form)
        self.mouseButton_l_u.action = "lu"
        self.mouseButton_l_u.setGeometry(QtCore.QRect(600, 10, 35, 35))
        self.mouseButton_l_u.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_l_u.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_l_u.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_l_u.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_l_u.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_l_u.setIcon(icon19)
        self.mouseButton_l_u.setObjectName(_fromUtf8("mouseButton_l_u"))
        
        self.mouseButton_r = QMouseButton(Form)
        self.mouseButton_r.action = "r"
        self.mouseButton_r.setGeometry(QtCore.QRect(680, 50, 35, 35))
        self.mouseButton_r.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_r.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_r.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_r.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_r.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_r.setIcon(icon20)
        self.mouseButton_r.setObjectName(_fromUtf8("mouseButton_r"))
        
        self.mouseButton_c = QMouseButton(Form)
        self.mouseButton_c.action = "c"
        self.mouseButton_c.setGeometry(QtCore.QRect(640, 50, 35, 35))
        self.mouseButton_c.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_c.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_c.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_c.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_c.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_c.setIcon(icon26)
        self.mouseButton_c.setObjectName(_fromUtf8("mouseButton_c"))
        
        self.mouseButton_l = QMouseButton(Form)
        self.mouseButton_l.action = "l"
        self.mouseButton_l.setGeometry(QtCore.QRect(600, 50, 35, 35))
        self.mouseButton_l.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_l.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_l.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_l.setText(_fromUtf8(""))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_l.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_l.setIcon(icon27)
        self.mouseButton_l.setObjectName(_fromUtf8("mouseButton_l"))
        
        self.mouseButton_c_l = QMouseButton(Form)
        self.mouseButton_c_l.action = "cl"
        self.mouseButton_c_l.setGeometry(QtCore.QRect(720, 10, 35, 35))
        self.mouseButton_c_l.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_c_l.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_c_l.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_c_l.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_c_l.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_c_l.setIcon(icon2)
        self.mouseButton_c_l.setObjectName(_fromUtf8("mouseButton_c_l"))
        
        self.mouseButton_c_r = QMouseButton(Form)
        self.mouseButton_c_r.action = "cr"
        self.mouseButton_c_r.setGeometry(QtCore.QRect(720, 50, 35, 35))
        self.mouseButton_c_r.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_c_r.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_c_r.setStyleSheet(_fromUtf8("color:blue"))
        self.mouseButton_c_r.setText(_fromUtf8(""))
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("img/mouse_c_r.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_c_r.setIcon(icon28)
        self.mouseButton_c_r.setObjectName(_fromUtf8("mouseButton_c_r"))
        
        self.mouseButton_back = QBackButton(Form)
        self.mouseButton_back.setGeometry(QtCore.QRect(720, 90, 35, 35))
        self.mouseButton_back.setMinimumSize(QtCore.QSize(35, 35))
        self.mouseButton_back.setMaximumSize(QtCore.QSize(35, 35))
        self.mouseButton_back.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.mouseButton_back.setText(_fromUtf8(""))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("img/web_go_text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mouseButton_back.setIcon(icon24)
        self.mouseButton_back.setObjectName(_fromUtf8("mouseButton_back"))
        #############################################################################################################
        
        
        self.moveButton_2_4 = QtGui.QPushButton(Form)
        self.moveButton_2_4.setGeometry(QtCore.QRect(490, 50, 35, 35))
        self.moveButton_2_4.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_2_4.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_2_4.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.moveButton_2_4.setText(_fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("img/Arrow2 - Down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveButton_2_4.setIcon(icon21)
        self.moveButton_2_4.setObjectName(_fromUtf8("moveButton_2_4"))
        self.moveButton_2_2 = QtGui.QPushButton(Form)
        self.moveButton_2_2.setGeometry(QtCore.QRect(410, 50, 35, 35))
        self.moveButton_2_2.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_2_2.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_2_2.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.moveButton_2_2.setText(_fromUtf8(""))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("img/Arrow2 - Right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveButton_2_2.setIcon(icon22)
        self.moveButton_2_2.setObjectName(_fromUtf8("moveButton_2_2"))
        self.moveButton_2_1 = QtGui.QPushButton(Form)
        self.moveButton_2_1.setGeometry(QtCore.QRect(370, 50, 35, 35))
        self.moveButton_2_1.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_2_1.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_2_1.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.moveButton_2_1.setText(_fromUtf8(""))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("img/Arrow2 - Left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveButton_2_1.setIcon(icon23)
        self.moveButton_2_1.setObjectName(_fromUtf8("moveButton_2_1"))
        self.webButton_back = QtGui.QPushButton(Form)
        self.webButton_back.setGeometry(QtCore.QRect(530, 210, 35, 35))
        self.webButton_back.setMinimumSize(QtCore.QSize(35, 35))
        self.webButton_back.setMaximumSize(QtCore.QSize(35, 35))
        self.webButton_back.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.webButton_back.setText(_fromUtf8(""))
        self.webButton_back.setIcon(icon24)
        self.webButton_back.setObjectName(_fromUtf8("webButton_back"))
        self.moveButton_2_3 = QtGui.QPushButton(Form)
        self.moveButton_2_3.setGeometry(QtCore.QRect(450, 50, 35, 35))
        self.moveButton_2_3.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_2_3.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_2_3.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.moveButton_2_3.setText(_fromUtf8(""))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("img/Arrow2 - Up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveButton_2_3.setIcon(icon25)
        self.moveButton_2_3.setObjectName(_fromUtf8("moveButton_2_3"))
        
        self.numButton_2_4 = QtGui.QPushButton(Form)
        self.numButton_2_4.setGeometry(QtCore.QRect(700, 170, 35, 35))
        self.numButton_2_4.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_2_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_2_4.setFont(font)
        self.numButton_2_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_4.setObjectName(_fromUtf8("numButton_2_4"))
        self.numButton_1_3 = QtGui.QPushButton(Form)
        self.numButton_1_3.setGeometry(QtCore.QRect(660, 130, 35, 35))
        self.numButton_1_3.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_1_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_1_3.setFont(font)
        self.numButton_1_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_3.setObjectName(_fromUtf8("numButton_1_3"))
        self.numButton_2_1 = QtGui.QPushButton(Form)
        self.numButton_2_1.setGeometry(QtCore.QRect(580, 170, 35, 35))
        self.numButton_2_1.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_2_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_2_1.setFont(font)
        self.numButton_2_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_1.setObjectName(_fromUtf8("numButton_2_1"))
        self.numButton_2_2 = QtGui.QPushButton(Form)
        self.numButton_2_2.setGeometry(QtCore.QRect(620, 170, 35, 35))
        self.numButton_2_2.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_2_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_2_2.setFont(font)
        self.numButton_2_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_2.setObjectName(_fromUtf8("numButton_2_2"))
        self.numButton_1_4 = QtGui.QPushButton(Form)
        self.numButton_1_4.setGeometry(QtCore.QRect(700, 130, 35, 35))
        self.numButton_1_4.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_1_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_1_4.setFont(font)
        self.numButton_1_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_4.setObjectName(_fromUtf8("numButton_1_4"))
        self.numButton_2_5 = QtGui.QPushButton(Form)
        self.numButton_2_5.setGeometry(QtCore.QRect(740, 170, 35, 35))
        self.numButton_2_5.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_2_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_2_5.setFont(font)
        self.numButton_2_5.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_5.setObjectName(_fromUtf8("numButton_2_5"))
        self.numButton_2_3 = QtGui.QPushButton(Form)
        self.numButton_2_3.setGeometry(QtCore.QRect(660, 170, 35, 35))
        self.numButton_2_3.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_2_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_2_3.setFont(font)
        self.numButton_2_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_2_3.setObjectName(_fromUtf8("numButton_2_3"))
        self.numButton_1_5 = QtGui.QPushButton(Form)
        self.numButton_1_5.setGeometry(QtCore.QRect(740, 130, 35, 35))
        self.numButton_1_5.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_1_5.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_1_5.setFont(font)
        self.numButton_1_5.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_5.setObjectName(_fromUtf8("numButton_1_5"))
        self.numButton_1_1 = QtGui.QPushButton(Form)
        self.numButton_1_1.setGeometry(QtCore.QRect(580, 130, 35, 35))
        self.numButton_1_1.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_1_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_1_1.setFont(font)
        self.numButton_1_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_1.setObjectName(_fromUtf8("numButton_1_1"))
        self.numButton_1_2 = QtGui.QPushButton(Form)
        self.numButton_1_2.setGeometry(QtCore.QRect(620, 130, 35, 35))
        self.numButton_1_2.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_1_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_1_2.setFont(font)
        self.numButton_1_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_1_2.setObjectName(_fromUtf8("numButton_1_2"))
        self.numButton_3_4 = QtGui.QPushButton(Form)
        self.numButton_3_4.setGeometry(QtCore.QRect(700, 210, 35, 35))
        self.numButton_3_4.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_3_4.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_3_4.setFont(font)
        self.numButton_3_4.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_4.setObjectName(_fromUtf8("numButton_3_4"))
        self.numButton_3_2 = QtGui.QPushButton(Form)
        self.numButton_3_2.setGeometry(QtCore.QRect(620, 210, 35, 35))
        self.numButton_3_2.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_3_2.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_3_2.setFont(font)
        self.numButton_3_2.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_2.setObjectName(_fromUtf8("numButton_3_2"))
        self.numButton_3_3 = QtGui.QPushButton(Form)
        self.numButton_3_3.setGeometry(QtCore.QRect(660, 210, 35, 35))
        self.numButton_3_3.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_3_3.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_3_3.setFont(font)
        self.numButton_3_3.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_3.setObjectName(_fromUtf8("numButton_3_3"))
        self.numButton_3_1 = QtGui.QPushButton(Form)
        self.numButton_3_1.setGeometry(QtCore.QRect(580, 210, 35, 35))
        self.numButton_3_1.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_3_1.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numButton_3_1.setFont(font)
        self.numButton_3_1.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.numButton_3_1.setObjectName(_fromUtf8("numButton_3_1"))
        self.numButton_back = QtGui.QPushButton(Form)
        self.numButton_back.setGeometry(QtCore.QRect(740, 210, 35, 35))
        self.numButton_back.setMinimumSize(QtCore.QSize(35, 35))
        self.numButton_back.setMaximumSize(QtCore.QSize(35, 35))
        self.numButton_back.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.numButton_back.setText(_fromUtf8(""))
        self.numButton_back.setIcon(icon24)
        self.numButton_back.setObjectName(_fromUtf8("numButton_back"))
        
        self.moveButton_back = QtGui.QPushButton(Form)
        self.moveButton_back.setGeometry(QtCore.QRect(530, 50, 35, 35))
        self.moveButton_back.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_back.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_back.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.moveButton_back.setText(_fromUtf8(""))
        self.moveButton_back.setIcon(icon24)
        self.moveButton_back.setObjectName(_fromUtf8("moveButton_back"))
        
        
        ########################################## MODE MOVE ##############################################
        self.modeButtonMove = QModeButton(Form)
        self.modeButtonMove.mode = "move"
        self.modeButtonMove.setGeometry(QtCore.QRect(40, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonMove.setFont(font)
        self.modeButtonMove.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonMove.setText(_fromUtf8(""))
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("img/modeMove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonMove.setIcon(icon29)
        self.modeButtonMove.setObjectName(_fromUtf8("modeButtonMove"))
        ########################################### MODE EMOT #############################################
        self.modeButtonEmot = QModeButton(Form)
        self.modeButtonEmot.mode = "emot"
        self.modeButtonEmot.setGeometry(QtCore.QRect(200, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonEmot.setFont(font)
        self.modeButtonEmot.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonEmot.setText(_fromUtf8(""))
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("img/modeEmot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonEmot.setIcon(icon30)
        self.modeButtonEmot.setObjectName(_fromUtf8("modeButtonEmot"))
        ########################################### MODE OFF  #############################################
        self.modeButtonOff = QModeButton(Form)
        self.modeButtonOff.mode = "off"
        self.modeButtonOff.setGeometry(QtCore.QRect(320, 50, 35, 35))
        self.modeButtonOff.setMinimumSize(QtCore.QSize(35, 35))
        self.modeButtonOff.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.modeButtonOff.setFont(font)
        self.modeButtonOff.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonOff.setText(_fromUtf8(""))
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("img/Standby.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonOff.setIcon(icon31)
        self.modeButtonOff.setObjectName(_fromUtf8("modeButtonOff"))
        ########################################### MODE GEAR #############################################
        self.modeButtonGear = QModeButton(Form)
        self.modeButtonGear.mode = "gear"
        self.modeButtonGear.setGeometry(QtCore.QRect(280, 50, 35, 35))
        self.modeButtonGear.setMinimumSize(QtCore.QSize(35, 35))
        self.modeButtonGear.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.modeButtonGear.setFont(font)
        self.modeButtonGear.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonGear.setText(_fromUtf8(""))
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8("img/Gears.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonGear.setIcon(icon32)
        self.modeButtonGear.setObjectName(_fromUtf8("modeButtonGear"))
        ########################################### MODE NUM  #############################################
        self.modeButtonNum = QModeButton(Form)
        self.modeButtonNum.mode = "num"
        self.modeButtonNum.setGeometry(QtCore.QRect(160, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonNum.setFont(font)
        self.modeButtonNum.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonNum.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/modeNumber.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonNum.setIcon(icon)
        self.modeButtonNum.setObjectName(_fromUtf8("modeButtonNum"))
        ########################################### MODE SYM  #############################################
        self.modeButtonSym = QModeButton(Form)
        self.modeButtonSym.mode = "sym"
        self.modeButtonSym.setGeometry(QtCore.QRect(120, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonSym.setFont(font)
        self.modeButtonSym.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/modeSymbol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonSym.setIcon(icon1)
        self.modeButtonSym.setObjectName(_fromUtf8("modeButtonSym"))
        ########################################### MODE MOUSE ############################################
        self.modeButtonMouse = QModeButton(Form)
        self.modeButtonMouse.mode = "mouse"
        self.modeButtonMouse.setGeometry(QtCore.QRect(0, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonMouse.setFont(font)
        self.modeButtonMouse.setStyleSheet(_fromUtf8("color:#fd750f"))
        self.modeButtonMouse.setText(_fromUtf8(""))
        self.modeButtonMouse.setIcon(icon2)
        self.modeButtonMouse.setObjectName(_fromUtf8("modeButtonMouse"))
        ############################################## MODE F #############################################
        self.modeButtonF = QModeButton(Form)
        self.modeButtonF.mode = "f?"
        self.modeButtonF.setGeometry(QtCore.QRect(240, 50, 35, 35))
        self.modeButtonF.setMinimumSize(QtCore.QSize(35, 35))
        self.modeButtonF.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.modeButtonF.setFont(font)
        self.modeButtonF.setStyleSheet(_fromUtf8("color:#ff0000"))
        self.modeButtonF.setObjectName(_fromUtf8("modeButtonF"))
        self.modeButtonF.setText(_translate("Form", "F?", None))
        ############################################## MODE WEB ###########################################
        self.modeButtonWeb = QModeButton(Form)
        self.modeButtonWeb.mode = "web"
        self.modeButtonWeb.setGeometry(QtCore.QRect(80, 50, 35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modeButtonWeb.setFont(font)
        self.modeButtonWeb.setAutoFillBackground(False)
        self.modeButtonWeb.setStyleSheet(_fromUtf8("color:#2496b6"))
        self.modeButtonWeb.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/modeWeb.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeButtonWeb.setIcon(icon3)
        self.modeButtonWeb.setObjectName(_fromUtf8("modeButtonWeb"))
        ###################################################################################################
        
        
        self.moveButton_1_3 = QtGui.QPushButton(Form)
        self.moveButton_1_3.setGeometry(QtCore.QRect(450, 10, 35, 35))
        self.moveButton_1_3.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_1_3.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_1_3.setStyleSheet(_fromUtf8("color:#5d4cab"))
        self.moveButton_1_3.setObjectName(_fromUtf8("moveButton_1_3"))
        self.moveButton_1_1 = QtGui.QPushButton(Form)
        self.moveButton_1_1.setGeometry(QtCore.QRect(370, 10, 35, 35))
        self.moveButton_1_1.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_1_1.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_1_1.setStyleSheet(_fromUtf8("color:#5d4cab"))
        self.moveButton_1_1.setObjectName(_fromUtf8("moveButton_1_1"))
        self.moveButton_1_5 = QtGui.QPushButton(Form)
        self.moveButton_1_5.setGeometry(QtCore.QRect(530, 10, 35, 35))
        self.moveButton_1_5.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_1_5.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_1_5.setStyleSheet(_fromUtf8("color:#5d4cab"))
        self.moveButton_1_5.setObjectName(_fromUtf8("moveButton_1_5"))
        self.moveButton_1_2 = QtGui.QPushButton(Form)
        self.moveButton_1_2.setGeometry(QtCore.QRect(410, 10, 35, 35))
        self.moveButton_1_2.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_1_2.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_1_2.setStyleSheet(_fromUtf8("color:#5d4cab"))
        self.moveButton_1_2.setObjectName(_fromUtf8("moveButton_1_2"))
        self.moveButton_1_4 = QtGui.QPushButton(Form)
        self.moveButton_1_4.setGeometry(QtCore.QRect(490, 10, 35, 35))
        self.moveButton_1_4.setMinimumSize(QtCore.QSize(35, 35))
        self.moveButton_1_4.setMaximumSize(QtCore.QSize(35, 35))
        self.moveButton_1_4.setStyleSheet(_fromUtf8("color:#5d4cab"))
        self.moveButton_1_4.setObjectName(_fromUtf8("moveButton_1_4"))
        
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.charButton_1_1.setText(_translate("Form", "q", None))
        self.charButton_1_2.setText(_translate("Form", "w", None))
        self.charButton_1_3.setText(_translate("Form", "e", None))
        self.charButton_1_4.setText(_translate("Form", "r", None))
        self.charButton_1_5.setText(_translate("Form", "t", None))
        self.charButton_1_7.setText(_translate("Form", "u", None))
        self.charButton_1_6.setText(_translate("Form", "y", None))
        self.charButton_1_8.setText(_translate("Form", "i", None))
        self.charButton_1_9.setText(_translate("Form", "o", None))
        self.charButton_3_8.setText(_translate("Form", "p", None))
        self.charButton_2_1.setText(_translate("Form", "a", None))
        self.charButton_2_2.setText(_translate("Form", "s", None))
        self.charButton_2_3.setText(_translate("Form", "d", None))
        self.charButton_2_4.setText(_translate("Form", "f", None))
        self.charButton_2_5.setText(_translate("Form", "g", None))
        self.charButton_2_6.setText(_translate("Form", "h", None))
        self.charButton_2_7.setText(_translate("Form", "j", None))
        self.charButton_2_8.setText(_translate("Form", "k", None))
        self.charButton_2_9.setText(_translate("Form", "l", None))
        self.charButton_3_9.setText(_translate("Form", "ñ", None))
        self.charButton_3_5.setText(_translate("Form", "b", None))
        self.charButton_3_4.setText(_translate("Form", "v", None))
        self.charButton_3_1.setText(_translate("Form", "z", None))
        self.charButton_3_6.setText(_translate("Form", "n", None))
        self.charButton_3_7.setText(_translate("Form", "m", None))
        self.charButton_3_3.setText(_translate("Form", "c", None))
        self.charButton_3_2.setText(_translate("Form", "x", None))
        self.funButton_1_2.setText(_translate("Form", "Ent", None))
        self.funButton_1_3.setText(_translate("Form", "Sup", None))
        
        self.funButton_1_6.setText(_translate("Form", "Esc", None))
        self.funButton_1_7.setText(_translate("Form", "Ins", None))
        self.funButton_1_8.setText(_translate("Form", "Ctl", None))
        self.funButton_1_9.setText(_translate("Form", "Alt", None))
        self.funButton_1_1.setText(_translate("Form", "May", None))
        self.funButton_1_5.setText(_translate("Form", "Imp", None))
        self.funButton_1_4.setText(_translate("Form", "Bsp", None))
        self.predectiveLineEdit_1.setText(_translate("Form", "Palabra 1", None))
        self.predectiveLineEdit_2.setText(_translate("Form", "Palabra 2", None))
        self.predectiveLineEdit_3.setText(_translate("Form", "Palabra 3", None))
        self.webButton_4_3.setText(_translate("Form", ".net", None))
        self.webButton_3_2.setText(_translate("Form", "/", None))
        self.webButton_4_4.setText(_translate("Form", ".org", None))
        self.webButton_3_3.setText(_translate("Form", ".", None))
        self.webButton_3_5.setText(_translate("Form", "_", None))
        self.webButton_4_1.setText(_translate("Form", "3w", None))
        self.webButton_3_1.setText(_translate("Form", "@", None))
        self.webButton_4_2.setText(_translate("Form", ".com", None))
        self.webButton_3_4.setText(_translate("Form", "-", None))
        self.numButton_2_4.setText(_translate("Form", "8", None))
        self.numButton_1_3.setText(_translate("Form", "2", None))
        self.numButton_2_1.setText(_translate("Form", "5", None))
        self.numButton_2_2.setText(_translate("Form", "6", None))
        self.numButton_1_4.setText(_translate("Form", "3", None))
        self.numButton_2_5.setText(_translate("Form", "9", None))
        self.numButton_2_3.setText(_translate("Form", "7", None))
        self.numButton_1_5.setText(_translate("Form", "4", None))
        self.numButton_1_1.setText(_translate("Form", "0", None))
        self.numButton_1_2.setText(_translate("Form", "1", None))
        self.numButton_3_4.setText(_translate("Form", "/", None))
        self.numButton_3_2.setText(_translate("Form", "-", None))
        self.numButton_3_3.setText(_translate("Form", "*", None))
        self.numButton_3_1.setText(_translate("Form", "+", None))
        self.moveButton_1_3.setText(_translate("Form", "Ini", None))
        self.moveButton_1_1.setText(_translate("Form", "Tab", None))
        self.moveButton_1_5.setText(_translate("Form", "AvP", None))
        self.moveButton_1_2.setText(_translate("Form", "Fin", None))
        self.moveButton_1_4.setText(_translate("Form", "ReP", None))

